# Generated by Django 3.1.2 on 2020-10-22 19:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import form_marketing.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=54)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=32)),
                ('view', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('template', models.FileField(blank=True, null=True, upload_to=form_marketing.models.template_dir)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViewPath',
            fields=[
                ('path', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('notified', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_marketing.business')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form_marketing.viewpath')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='business',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form_marketing.campaign'),
        ),
    ]
